blank_issues_enabled: true
contact_links:
  - name: ğŸ†• Create new issue
    url: https://www.naver.com
    about: ì–´ë– í•œ ì¼€ì´ìŠ¤ì— ëŒ€í•œ ì´ìŠˆë¼ë„ ë³´ê³  í•´ì£¼ì‹œë©´ ê°ì‚¬í•˜ê² ìŠµë‹ˆë‹¤. ğŸ˜“